# Site settings
title: My Gamaers! fan blog.
description: Vitaly Ford
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Scourgerr
user_description: Cool guy. Always wins at Among us.
user_title: Freakin Epic
email: bclemowit@arcadia.edu
twitter_username: nO
github_username:  idk
gplus_username:  maybe

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
